### ISSUE TITLE
MVP - CREATE 

### ISSUE THREAD

**Issue by GregM1992** [nss-evening-cohort-24/hack-client-awareness-campaign#9]
# User Story
As an authenticated user I should be able to create a Campaign to render on the campaign page by filling out a form that takes the following input:
 - campaign name
 - image url
 - short description
 - campaign type

# Acceptance Criteria
When the user naviagates to the campign form they should be met with a set of input fields that allows the submission of the following:
- name
- imageURL
- description
- and a set of radials that allow multiple selections for the campaign category

When the form is submitted a post node is created in the database. this node will contain the following:
- id 
- imageURL
- userId
- name 
- description

this will also make PostCategory node which will contain the following:
- id 
- PostId
- CategoryId

 Then a campaign card should render on the page showing the following:
- name
- image
- description 
- edit button (if created by the user)
- delete button (if created by the user)

# Dependecies
#8 
#7 

# Dev Notes

**Comment by keanacobarde** [comment]
Create functionality has been successfully implemented and tested. Closing ticket.
